export { createRenderer } from './renderer'
export { h } from './h'
export { Text, Fragment } from './vNode'
export { getCurrentInstance } from './component'
export { onBeforeMount, onMounted, onBeforeUpdate, onUpdated } from './apiLifecycle'
export * from '@vue/reactivity'